dist: xenial
language: go
go:
  - "1.12.4"
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
env:
  GO111MODULE: "on"
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)