// Code generated by "stringer -type=Color"; DO NOT EDIT.

package main

import "strconv"

const _Color_name = "RedGreenYellow"

var _Color_index = [...]uint8{0, 3, 8, 14}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
