// Code generated by codecgen - DO NOT EDIT.

package sca

import (
	"errors"
	codec1978 "github.com/ugorji/go/codec"
	"runtime"
	"strconv"
)

const (
	// ----- content types ----
	codecSelferCcUTF88943 = 1
	codecSelferCcRAW8943  = 255
	// ----- value types used ----
	codecSelferValueTypeArray8943  = 10
	codecSelferValueTypeMap8943    = 9
	codecSelferValueTypeString8943 = 6
	codecSelferValueTypeInt8943    = 2
	codecSelferValueTypeUint8943   = 3
	codecSelferValueTypeFloat8943  = 4
	codecSelferBitsize8943         = uint8(32 << (^uint(0) >> 63))
)

var (
	errCodecSelferOnlyMapOrArrayEncodeToStruct8943 = errors.New(`only encoded map or array can be decoded into a struct`)
)

type codecSelfer8943 struct{}

func init() {
	if codec1978.GenVersion != 10 {
		_, file, _, _ := runtime.Caller(0)
		panic("codecgen version mismatch: current: 10, need " + strconv.FormatInt(int64(codec1978.GenVersion), 10) + ". Re-generate file: " + file)
	}
	if false {
		var _ byte = 0 // reference the types, but skip this branch at build/run time
	}
}

func (x DataObject) CodecEncodeSelf(e *codec1978.Encoder) {
	var h codecSelfer8943
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	if x == nil {
		r.EncodeNil()
	} else {
		if false {
		} else if yyxt1 := z.Extension(z.I2Rtid(x)); yyxt1 != nil {
			z.EncExtension(x, yyxt1)
		} else {
			h.encDataObject((DataObject)(x), e)
		}
	}
}

func (x *DataObject) CodecDecodeSelf(d *codec1978.Decoder) {
	var h codecSelfer8943
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r
	if false {
	} else if yyxt1 := z.Extension(z.I2Rtid(x)); yyxt1 != nil {
		z.DecExtension(x, yyxt1)
	} else {
		h.decDataObject((*DataObject)(x), d)
	}
}

func (x codecSelfer8943) encDataObject(v DataObject, e *codec1978.Encoder) {
	var h codecSelfer8943
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	r.EncodeStringBytesRaw([]byte(v))
}

func (x codecSelfer8943) decDataObject(v *DataObject, d *codec1978.Decoder) {
	var h codecSelfer8943
	z, r := codec1978.GenHelperDecoder(d)
	_, _, _ = h, z, r
	*v = r.DecodeBytes(*((*[]byte)(v)), false)
}
